import { getTenantConfig } from "@/config/tenants";

interface DemoPageProps {
  params: Promise<{ tenant: string }>;
}

const CSS_VARS = [
  "background",
  "foreground",
  "card",
  "card-foreground",
  "primary",
  "primary-foreground",
  "secondary",
  "secondary-foreground",
  "muted",
  "muted-foreground",
  "accent",
  "accent-foreground",
  "destructive",
  "destructive-foreground",
  "border",
  "input",
  "ring",
] as const;

export default async function DemoPage({ params }: DemoPageProps) {
  const { tenant } = await params;
  const config = getTenantConfig(tenant);

  return (
    <div className="mx-auto max-w-7xl px-4 py-12">
      <div className="mb-8 space-y-3">
        <div className="flex items-center gap-2">
          <span className="rounded-md bg-secondary px-2 py-1 text-xs text-secondary-foreground">
            {config.slug}
          </span>
          <span className="rounded-md border border-border px-2 py-1 text-xs">
            Theme Demo
          </span>
        </div>
        <h1 className="text-3xl font-bold tracking-tight">
          <span className="text-primary">{config.name}</span> — Theme Showcase
        </h1>
        <p className="max-w-2xl text-muted-foreground">
          This page showcases all the theme tokens available for your
          components. Each tenant gets a unique color palette generated by
          Dheme.
        </p>
      </div>

      {/* Color Tokens */}
      <section className="mb-12">
        <h2 className="mb-4 text-xl font-semibold">Color Tokens</h2>
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {CSS_VARS.map((name) => (
            <div
              key={name}
              className="flex items-center gap-3 rounded-lg border border-border p-3"
            >
              <div
                className="h-10 w-10 shrink-0 rounded-md border border-border"
                style={{ backgroundColor: `var(--${name})` }}
              />
              <div>
                <p className="font-mono text-sm">--{name}</p>
                <p className="text-xs text-muted-foreground">var(--{name})</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* UI Elements Preview */}
      <section className="mb-12">
        <h2 className="mb-4 text-xl font-semibold">UI Elements</h2>
        <div className="space-y-4">
          {/* Buttons */}
          <div className="rounded-lg border border-border p-4">
            <h3 className="mb-3 font-medium">Buttons</h3>
            <div className="flex flex-wrap gap-2">
              <button className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90">
                Primary
              </button>
              <button className="rounded-md bg-secondary px-4 py-2 text-sm font-medium text-secondary-foreground transition-colors hover:bg-secondary/80">
                Secondary
              </button>
              <button className="rounded-md border border-input bg-background px-4 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground">
                Outline
              </button>
              <button className="rounded-md bg-destructive px-4 py-2 text-sm font-medium text-destructive-foreground transition-colors hover:bg-destructive/90">
                Destructive
              </button>
            </div>
          </div>

          {/* Cards */}
          <div className="rounded-lg border border-border p-4">
            <h3 className="mb-3 font-medium">Cards</h3>
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              <div className="rounded-lg border border-border bg-card p-4 text-card-foreground shadow-sm">
                <h4 className="font-semibold">Card Title</h4>
                <p className="mt-1 text-sm text-muted-foreground">
                  This is a card with the default styling.
                </p>
              </div>
              <div className="rounded-lg bg-muted p-4">
                <h4 className="font-semibold">Muted Card</h4>
                <p className="mt-1 text-sm text-muted-foreground">
                  This card uses muted background.
                </p>
              </div>
              <div className="rounded-lg bg-accent p-4 text-accent-foreground">
                <h4 className="font-semibold">Accent Card</h4>
                <p className="mt-1 text-sm opacity-80">
                  This card uses accent colors.
                </p>
              </div>
            </div>
          </div>

          {/* Inputs */}
          <div className="rounded-lg border border-border p-4">
            <h3 className="mb-3 font-medium">Form Elements</h3>
            <div className="flex flex-wrap gap-4">
              <input
                type="text"
                placeholder="Text input"
                className="rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
              />
              <select className="rounded-md border border-input bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-ring">
                <option>Select option</option>
                <option>Option 1</option>
                <option>Option 2</option>
              </select>
            </div>
          </div>

          {/* Text Styles */}
          <div className="rounded-lg border border-border p-4">
            <h3 className="mb-3 font-medium">Typography</h3>
            <div className="space-y-2">
              <p className="text-foreground">
                Regular text uses{" "}
                <code className="rounded bg-muted px-1 py-0.5 text-sm">
                  foreground
                </code>
              </p>
              <p className="text-muted-foreground">
                Muted text uses{" "}
                <code className="rounded bg-muted px-1 py-0.5 text-sm">
                  muted-foreground
                </code>
              </p>
              <p className="text-primary">
                Primary text uses{" "}
                <code className="rounded bg-muted px-1 py-0.5 text-sm">
                  primary
                </code>
              </p>
              <p className="text-destructive">
                Destructive text uses{" "}
                <code className="rounded bg-muted px-1 py-0.5 text-sm">
                  destructive
                </code>
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Radius Preview */}
      <section>
        <h2 className="mb-4 text-xl font-semibold">Border Radius</h2>
        <p className="mb-4 text-sm text-muted-foreground">
          The <code className="rounded bg-muted px-1 py-0.5">--radius</code>{" "}
          variable controls the default border radius.
        </p>
        <div className="flex flex-wrap gap-4">
          <div
            className="flex h-20 w-20 items-center justify-center border border-border bg-card text-xs"
            style={{ borderRadius: "var(--radius)" }}
          >
            --radius
          </div>
          <div
            className="flex h-20 w-20 items-center justify-center border border-border bg-card text-xs"
            style={{ borderRadius: "calc(var(--radius) * 2)" }}
          >
            2x radius
          </div>
          <div
            className="flex h-20 w-20 items-center justify-center border border-border bg-card text-xs"
            style={{ borderRadius: "calc(var(--radius) * 0.5)" }}
          >
            0.5x radius
          </div>
        </div>
      </section>
    </div>
  );
}
